# Generated by Django 5.2.2 on 2025-06-09 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_lote', models.CharField(max_length=50, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Minimercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_minimercado', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_oferta', models.CharField(default='', max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descuento_porcetaje', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('precio', models.PositiveIntegerField(default=0)),
                ('costo', models.PositiveIntegerField(default=0)),
                ('minimal_stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=30, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Oferta_vencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('new_code_bar', models.CharField(max_length=50)),
                ('oferta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_vencimiento', to='Tienda.oferta')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_vencimiento', to='Tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_producto', to='Tienda.oferta')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_producto', to='Tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad_inicial', models.PositiveIntegerField(default=1)),
                ('cantidad_disponible', models.PositiveIntegerField(default=1)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_relacionados', to='Tienda.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_asociados', to='Tienda.producto')),
            ],
            options={
                'verbose_name': 'Relación Lote-Producto',
                'verbose_name_plural': 'Relaciones Lote-Producto',
                'unique_together': {('lote', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='productos',
            field=models.ManyToManyField(through='Tienda.LoteProducto', to='Tienda.producto'),
        ),
        migrations.AddField(
            model_name='lote',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='Tienda.proveedor'),
        ),
        migrations.CreateModel(
            name='Registro_compra_proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio_unitario', models.PositiveIntegerField(default=0)),
                ('valor_total', models.PositiveIntegerField(default=0)),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('cantidad_articulos', models.PositiveIntegerField(default=0)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio_unitario', models.PositiveIntegerField(default=0)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Tienda.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Tienda.venta')),
            ],
        ),
    ]
