# Generated by Django 5.2 on 2025-05-02 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minimercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_minimercado', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='oferta',
            old_name='porcentaje_descuento',
            new_name='descuento_porcetaje',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='oferta',
            name='tipo_oferta',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='minimal_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Oferta_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_producto', to='Tienda.oferta')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_producto', to='Tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta_vencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('new_code_bar', models.CharField(max_length=50)),
                ('oferta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_vencimiento', to='Tienda.oferta')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_vencimiento', to='Tienda.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_lote', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('productos', models.ManyToManyField(to='Tienda.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.proveedor')),
            ],
        ),
    ]
