# Generated by Django 5.2.2 on 2025-06-08 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_alter_proveedor_rut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Lote', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AlterModelOptions(
            name='loteproducto',
            options={'verbose_name': 'Relación Lote-Producto', 'verbose_name_plural': 'Relaciones Lote-Producto'},
        ),
        migrations.AlterField(
            model_name='lote',
            name='code_lote',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='Tienda.proveedor'),
        ),
        migrations.AlterField(
            model_name='loteproducto',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_relacionados', to='Tienda.lote'),
        ),
        migrations.AlterField(
            model_name='loteproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_asociados', to='Tienda.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='loteproducto',
            unique_together={('lote', 'producto')},
        ),
    ]
