# Generated by Django 5.2 on 2025-05-02 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_minimercado_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.producto')),
            ],
        ),
        migrations.AlterField(
            model_name='lote',
            name='productos',
            field=models.ManyToManyField(through='Tienda.LoteProducto', to='Tienda.producto'),
        ),
    ]
