# Generated by Django 5.2.2 on 2025-07-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
