# Generated by Django 5.2.2 on 2025-07-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_proveedor_verify_digit_alter_proveedor_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='verify_digit',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('K', 'K')], default='0', max_length=1),
        ),
    ]
