# Generated by Django 5.2.2 on 2025-07-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0007_alter_proveedor_verify_digit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
