# Generated by Django 5.2.2 on 2025-07-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0008_alter_oferta_fecha_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaVencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descuento_porcentaje', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('dias_antes_vencimiento', models.PositiveIntegerField(default=3, help_text='Días antes del vencimiento para aplicar la oferta')),
            ],
        ),
        migrations.RemoveField(
            model_name='oferta_vencimiento',
            name='oferta_id',
        ),
        migrations.RemoveField(
            model_name='oferta_producto',
            name='oferta_id',
        ),
        migrations.RemoveField(
            model_name='oferta_producto',
            name='producto_id',
        ),
        migrations.RemoveField(
            model_name='oferta_vencimiento',
            name='producto_id',
        ),
        migrations.CreateModel(
            name='OfertaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descuento_porcentaje', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('productos', models.ManyToManyField(related_name='ofertas_producto', to='Tienda.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Oferta',
        ),
        migrations.DeleteModel(
            name='Oferta_producto',
        ),
        migrations.DeleteModel(
            name='Oferta_vencimiento',
        ),
    ]
