# Generated by Django 5.2.2 on 2025-07-03 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0009_ofertavencimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('stock_bajo', 'Producto Bajo en Stock'), ('proximo_vencer', 'Producto Próximo a Vencer'), ('oferta_terminando', 'Oferta Próxima a Terminar')], max_length=20)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('mostrada', 'Mostrada'), ('desactivada', 'Desactivada')], default='activa', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_mostrada', models.DateTimeField(blank=True, null=True)),
                ('umbral_stock', models.PositiveIntegerField(blank=True, help_text='Stock mínimo para activar alerta', null=True)),
                ('dias_anticipacion', models.PositiveIntegerField(blank=True, help_text='Días de anticipación para alertas de vencimiento', null=True)),
                ('activa', models.BooleanField(default=True)),
                ('oferta_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tienda.ofertaproducto')),
                ('oferta_vencimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tienda.ofertavencimiento')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tienda.producto')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
