# Generated by Django 5.2.2 on 2025-07-03 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0010_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_forma', models.CharField(choices=[('cuadrado', 'Cuadrado'), ('rectangulo', 'Rectángulo')], default='rectangulo', max_length=20)),
                ('posicion_x', models.FloatField(default=0)),
                ('posicion_y', models.FloatField(default=0)),
                ('ancho', models.FloatField(default=100)),
                ('alto', models.FloatField(default=100)),
                ('color', models.CharField(default='#3498db', help_text='Color en formato hexadecimal', max_length=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sección de Bodega',
                'verbose_name_plural': 'Secciones de Bodega',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SeccionLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seccion_asignada', to='Tienda.lote')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_asignados', to='Tienda.seccionbodega')),
            ],
            options={
                'verbose_name': 'Asignación Sección-Lote',
                'verbose_name_plural': 'Asignaciones Sección-Lote',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('seccion', 'lote')},
            },
        ),
    ]
