# Generated by Django 5.2.2 on 2025-07-04 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0011_seccionbodega_seccionlote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reporte', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('producto', 'Reporte de Producto'), ('perdida', 'Pérdida de Producto'), ('inventario', 'Reporte de Inventario'), ('ventas', 'Reporte de Ventas')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ReporteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.producto')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_reporte', to='Tienda.reporte')),
            ],
            options={
                'verbose_name': 'Producto en Reporte',
                'verbose_name_plural': 'Productos en Reporte',
                'unique_together': {('reporte', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='reporte',
            name='productos_afectados',
            field=models.ManyToManyField(blank=True, through='Tienda.ReporteProducto', to='Tienda.producto'),
        ),
    ]
