# Generated by Django 5.2.2 on 2025-07-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0012_reporte_reporteproducto_reporte_productos_afectados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteproducto',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
