# Generated by Django 5.2.2 on 2025-07-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0013_alter_reporteproducto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='minimercado',
            name='nombre_minimercado',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ofertaproducto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ofertavencimiento',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_proveedor',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='nombre_reporte',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='seccionbodega',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
