# Generated by Django 5.2.2 on 2025-07-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0015_alter_alert_dias_anticipacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='dias_anticipacion',
            field=models.PositiveIntegerField(blank=True, help_text='Días de anticipación para alertas de vencimiento', null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='umbral_stock',
            field=models.PositiveIntegerField(blank=True, help_text='Stock mínimo para activar alerta', null=True),
        ),
    ]
